Nightmarket fest UI change
TGDF/official-site pull request #459
Opened 2022-04-29 08:22 UTC by arch-jslin

as title

2022-04-29 09:04 UTC, elct9620 commented
Please update `features/night_market.feature` to click correct menu text after translation is added.

2022-04-30 06:39 UTC, arch-jslin commented
feature request updated

2022-05-01 12:53 UTC, elct9620 requested changes

2022-05-01 12:53 UTC, elct9620 commented on features/night_market.feature
> +  @night_market_enabled
The E2E test failed is due to `And I click "Night Market" in menu` should be `And I click "遊戲夜市" in menu` in the scenario. We didn't need to add a test for this scenario.

2022-05-05 07:05 UTC, arch-jslin commented
E2E test updated. The final feature test is marked "pending" because there are no feature tests for button translation correctness.

2022-05-05 07:36 UTC, arch-jslin reviewed
@elct9620 please see if you can approve the review now.

2022-05-05 07:36 UTC, arch-jslin commented on features/night_market.feature
> +  @night_market_enabled
I think I've fixed all feature tests

2022-05-05 07:38 UTC, merged